### ISSUE TITLE
Could not load file or assembly 'dynamic.base.156'

### ISSUE THREAD

**Issue by kouta-kun** [sboxgame/issues#2010]
### Describe the bug

Once in a while (not consistently), while trying to hotload a gamemode I get the following error message:
`Unable to load one or more of the requested types. Could not load file or assembly 'dynamic.base.156, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'`. It goes away after closing and re-opening sbox so it's not a compilation issue I think.

### To Reproduce

It's not consistent and I haven't found any change pattern that manages to reproduce it. That being said, it happens pretty often for me, so the steps probably go something like
1. Start up a game mode
2. Make changes to it
3. Repeat 2 until it happens

### Expected behavior

Hotload correctly, or at least bring up a message telling me my changes are not compatible and I should reload

**Comment by trundler-dev** [comment]
Here are some better steps to reproduce:

1. Go into a game.
2. Leave the game.
3. Change a local game's code so it does not compile.
4. Fix the code.
5. Observe the error.

**Comment by handsomematt** [comment]
```
2022/07/22 00:33:54.716	CompileManager	Building 1 compilers	
2022/07/22 00:33:54.918	Generic	Unable to load one or more of the requested types.
Could not load file or assembly 'dynamic.base.103, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.	System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'dynamic.base.103, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Sandbox.Internal.TypeLibrary.AddAssembly(Assembly incoming, Boolean isDynamic) in C:\git\sbox\engine\Sandbox.Reflection\TypeLibrary\TypeLibrary.cs:line 112
   at Sandbox.Internal.TypeLibrary.AddAssembly(AssemblyRegistation options) in C:\git\sbox\engine\Sandbox.Reflection\TypeLibrary\TypeLibrary.cs:line 233
   at Sandbox.ToolsDll.OnAddonsCompiled(Compiler[] compiled) in C:\git\sbox\engine\Sandbox.Tools\ToolsDll.cs:line 140
   at Sandbox.ServerAddons.CompileAndHotloadAsync() in C:\git\sbox\engine\Sandbox.Engine\Addon\ServerAddons.cs:line 168
System.IO.FileNotFoundException: Could not load file or assembly 'dynamic.base.103, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'dynamic.base.103, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'dynamic.base.103, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'dynamic.base.103, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Sandbox.Internal.LoadContext.Load(AssemblyName assemblyName) in C:\git\sbox\engine\Sandbox.Reflection\TypeLibrary\LoadContext.cs:line 23
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```
