### ISSUE TITLE
Deleting project files via Explorer.exe breaks entire game and requires complete reinstall.

### ISSUE THREAD

**Issue by LiminalCrab** [sboxgame/issues#2757]
### Describe the bug

I had several thousand textures I was experimenting with, and when I finally went to delete them to begin reorganizing them I did some through Windows explorer. When I restarted S&box to get asset browser to update I could no longer launch the dev tools or the standalone game. I attempted to verify integrity of game cache with no success. Complete reinstall of the game was required to get it to run again.

I did this several times in the past with success; however I only ran into issues this time around so I included log files at the bottom.

### To Reproduce

1. Add .vmats to materials folder through Sbox's asset browser.
2. Delete them through windows explorer.exe
3. Restart the dev tools and or game.

### Expected behavior

The files should be deleted, and no game file corruptions should occur.

### Logs
https://cdn.al3f.com/sbox/logs.zip

### Additional context

```C#
2023/01/07 11:40:11.0015	Interop	The path `/D:/Projects/sbox/karakyo/materials` cannot contain the `:` character	System.NotSupportedException: The path `/D:/Projects/sbox/karakyo/materials` cannot contain the `:` character
   at Zio.FileSystems.FileSystem.ValidatePathImpl(UPath path, String name)
   at Zio.FileSystems.FileSystem.ValidatePath(UPath path, String name, Boolean allowNull)
   at Zio.FileSystems.FileSystem.DirectoryExists(UPath path)
   at Zio.FileSystems.SubFileSystem..ctor(IFileSystem fileSystem, UPath subPath, Boolean owned)
   at Sandbox.BaseFileSystem.CreateSubSystem(String path)
   at Sandbox.BaseFileSystem.CreateAndMount(BaseFileSystem system, String path)
   at Editor.ToolAddon..ctor(String addonFilePath, CompileGroup compileGroup)
   at Editor.ToolAddonManager.TryAddAddon(String addonFile)
   at Editor.ToolAddonManager.RebuildAddons()
   at Editor.ManagedTools.InitStart()
   at Managed.SourceTools.Exports.Editor_ManagedTools_InitStart()
2023/01/07 11:40:12.0095	engine/AssetSystem	AssetSystem pruned 2 stale assets	
2023/01/07 11:40:16.7327	Interop	Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.ToolsDll.OnPostBoostrap()
   at Sandbox.Engine.Bootstrap.Init()
   at Managed.SandboxEngine.Exports.SandboxEngine_Bootstrap_Init()
2023/01/07 11:40:16.7366	engine/Engine	Bootstrap::Init returned false	
```

**Comment by LiminalCrab** [comment]
These might be related: https://github.com/sboxgame/issues/issues/2750
