### ISSUE TITLE
NativeEngine.NavPath.ComputePathPosToPos Is Not Thread Safe

### ISSUE THREAD

**Issue by anthonysharpy** [sboxgame/issues#2961]
### Describe the bug

If you try to run the nav mesh generator in a separate thread it can sometimes crash the game. Never crashes when run on the main thread.

Application: sbox-dev.exe
CoreCLR Version: 7.0.222.60605
.NET Version: 7.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at NativeEngine.NavPath.ComputePathPosToPos(NativeEngine.PathCapabilities, Vector3, Vector3, NativeEngine.NavPathCostBase)
   at Sandbox.NavPathBuilder.Build(Vector3)
   at LameRP.NPCBase.GetNavMeshPathToDestination(Vector3)
   at LameRP.NPCBase.GetPathToNextRouteStop()
   at LameRP.NPCBase.SetRoute(System.Collections.Generic.List`1<Vector3>, Single)
   at LameRP.Citizen+<>c__DisplayClass4_0.<SawSomethingDangerous>b__0()
   at Sandbox.TaskSource+WorkerThreadAction+<>c.<.cctor>b__21_0(System.Object)
   at Sandbox.Tasks.ExpirableSynchronizationContext.ProcessQueue()
   at Sandbox.Tasks.WorkerThread+<WorkerTask>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Sandbox.Tasks.WorkerThread.WorkerTask()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()

In this case I was calling it inside a GameTask.RunInThreadAsync. Not sure if it's relevant to reproducing it but I was also spawning a lot of these threads at the same time (1-30).

Would be nice if this could work in multiple threads since generating paths can be quite costly for some use cases. Although maybe it already does that under the hood?

### To Reproduce

Too much code to post here. Can send a copy of the project on request.

### Expected behavior

Doesn't crash.

**Comment by anthonysharpy** [comment]
probably would help to mention that this is how i invoke it. obviously you can just replace my nonsense constants with actual values.

```
var pathBuilder = NavMesh.PathBuilder(Position)
	.WithMaxClimbDistance( HEIGHT / 2 )
	.WithMaxDropDistance( HEIGHT / 2 )
	.WithStepHeight( HEIGHT * 0.32f )
	.WithMaxDistance( 1000000 );

if (ALLOW_PARTIAL_PATHS)
	pathBuilder = pathBuilder.WithPartialPaths();

var path = pathBuilder.Build( end );
```
