### ISSUE TITLE
`Websocket.Connect` throws an error on success

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#2980]
### Describe the bug

Connecting to a websocket works but it still throws an error for some reason, this error does not break anything.

## Code
```csharp
public Backend()
{
    socket = new Sandbox.WebSocket();
    socket.OnMessageReceived += HandleMessageReceived;
    _ = TryConnectToWebSocket();
}

private async Task TryConnectToWebSocket()
{
    try
    {
        await socket.Connect(websocketUri);
    }
    catch (Exception error)
    {
        Log.Error("Unable to connect to the remote WebSocket server!");
    };
}
```

## Error

` 10:46:54   Server 'c' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.`

```
'c' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonReaderException: 'c' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
```

**Comment by timmybo5** [comment]
Changing around some stuff and it seems this is not related to the connecting itself, all good :)
