### ISSUE TITLE
 Temporary RT "RenderTarget_ScrWxScrH" wasn't released! when using Vignette postprocess

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#3128]
### Describe the bug

The console gets flooded with the following error:

```
Temporary RT "RenderTarget_1020x574" wasn't released!
   at Sandbox.RenderTarget.Tick()
   at Sandbox.EngineLoop.FrameStart()
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
   at Sandbox.SourceEngineApp.RunFrame() in C:\build_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 46
   at Sandbox.SourceEngineApp.RunLoop() in C:\build_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 37
   at Sandbox.Program.LaunchGame() in C:\build_work\sbox\sbox\engine\Launcher\Launcher.cs:line 100
   at Sandbox.Program.Main() in C:\build_work\sbox\sbox\engine\Launcher\Launcher.cs:line 50
```

When using the following snippet of code:
```
var postProcess = Camera.Main.FindOrCreateHook<Sandbox.Effects.ScreenEffects>();

postProcess.Vignette.Intensity = 1f;
postProcess.Vignette.Roundness = 1f;
postProcess.Vignette.Smoothness = 1f;
postProcess.Vignette.Color = Color.Red;
```

### To Reproduce

:)

### Expected behavior

:)

### Media/Files

![image](https://user-images.githubusercontent.com/59583743/231289091-122e6240-bd00-45c8-a509-af6bf8236960.png)

**Comment by timmybo5** [comment]
Having the same issue here, seems to randomly stop
![image](https://user-images.githubusercontent.com/4988198/231525726-ded2ba69-d668-4370-924e-14b8effe7281.png)

**Comment by trende2001** [comment]
Happens on dm98 as well (has vignette too)

**Comment by handsomematt** [comment]
@samzanemesis https://github.com/Facepunch/sbox/commit/6ee43b38e629221c8b8faa2c43d6eb3fa81f6afb

**Comment by samzanemesis** [comment]
Shouldn't happen anymore

This isn't the ideal fix as what was causing this in the first place was causing another (less severe) bug, having a reproduction step helps a lot

**Comment by jason11040** [comment]
I was also getting the spam log but now i think it's spamming this for me.
C:\build\_work\sbox\sbox\src\rendersystem\texturebase.cpp(3556):ResourceHandleToData(  ) failed! Falling back to error texture!

**Comment by handsomematt** [comment]
Should be fine now
