### ISSUE TITLE
Can't start any gamemode after I cancel downloading files from a host in a private gamemode.

### ISSUE THREAD

**Issue by eEight-dev** [sboxgame/issues#3283]
### Describe the bug

I cancel downloading files from a host in a private gamemode, I open a lobby, I start a new game then I get an error and I'm kicked back to the main menu.

### To Reproduce

1. Open S&box (either dev or non-dev mode).
2. Join a private gamemode in the server list.
3. Now it automatically downloads missing files from the server host.
4. Cancel the download.
5. Go back to main menu.
6. Open a lobby and select any gamemode.
7. Start the gamemode.
8. Now you get a "Object reference not set to an instance of an object." error and you are kicked back to the main menu.

### Expected behavior

I expect to be able to start a new gamemode without errors. I can only fix this if I restart S&box. If I start downloading missing files again from a host and then create a new gamemode, same thing happens.

### Media/Files

![1](https://github.com/sboxgame/issues/assets/120290229/f32e1764-231e-4dda-9e8c-7d0723561a49)

**Comment by DevulTj** [comment]
Can you provide the stack trace for this? Either by using the editor and click on the error in the console, or grab it from your `/Logs/*.log` file.

**Comment by eEight-dev** [comment]
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Input.SetupManifestData()
   at Sandbox.Input.InitializeInputActions()
   at Sandbox.ClientDll.Sandbox.Engine.IClientDll.OnServerInfo(ServerInformation serverInfo)
   at Sandbox.NetworkClient.ProcessServerInfo(String manifest, String mapname)
   at Managed.SandboxEngine.Exports.Sandbox_INetworkClient_ProcessServerInfo(UInt32 self, IntPtr manifest, IntPtr mapname)

This?

**Comment by DevulTj** [comment]
Perfect, thank you.

**Comment by eEight-dev** [comment]
Unfortunately this still happens. I also just did a quick reinstall to make sure.

Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.InputManifestTemplate.TransformText()
   at Sandbox.Input.InitializeInputActions()
   at Sandbox.ClientDll.Sandbox.Engine.IClientDll.OnServerInfo(ServerInformation serverInfo)
   at Sandbox.NetworkClient.ProcessServerInfo(String manifest, String mapname)
   at Managed.SandboxEngine.Exports.Sandbox_INetworkClient_ProcessServerInfo(UInt32 self, IntPtr manifest, IntPtr mapname)

This is what it says this time.

**Comment by DevulTj** [comment]
Oh fun, that's another stack trace, but I'll fix that too

**Comment by DevulTj** [comment]
Appreciated, I'll sort it
