### ISSUE TITLE
Cannot set WebSurface Url 

### ISSUE THREAD

**Issue by Remscar** [sboxgame/issues#3286]
### Describe the bug

Since the latest update when I try to set the URL on a WebSurface I get two errors:

```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Value cannot be null. (Parameter 'uriString'))
System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Uri..ctor(String uriString)
   at Sandbox.WebSurface.CheckUrlIsAllowed(String url)
   at Sandbox.WebSurface.set_Url(String value)
   at Sandbox.WebSurface.<>c__DisplayClass28_0.<set_Url>b__0()
   at Sandbox.WebSurface.CreateAsync()
```
![image](https://github.com/sboxgame/issues/assets/3459787/e7a8a966-a6c6-4f82-a8ec-95b1d5f0d9e3)

And immediately after:
```
Value cannot be null. (Parameter 'uriString')
System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Uri..ctor(String uriString)
   at Sandbox.WebSurface.CheckUrlIsAllowed(String url)
   at Sandbox.WebSurface.set_Url(String value)
   at Sandbox.WebSurface.<>c__DisplayClass28_0.<set_Url>b__0()
   at Sandbox.WebSurface.CreateAsync()
```
![image](https://github.com/sboxgame/issues/assets/3459787/423deb68-b5f8-4800-bf81-a6c785213355)

I have tried to whitelist the URL's of the requests:
"https://i.pinimg.com/originals/62/c7/c2/62c7c28439ff95418a16b0d0c907fa18.jpg" => "https://i.pinimg/com/"
and 
"https://www.youtube.com/embed/XkfmrXLxaNk?autoplay=0;frameborder=0" => "https://www.youtube.com/"

But it seems to have no effect

### To Reproduce

```
using Sandbox;
using Sandbox.UI;
using System;

namespace Cinema;

public partial class WebMediaSource : WorldPanel
{
    private WebSurface WebSurface;
    public Texture WebTexture;

    public string CurrentUrl => WebSurface.Url;

    public WebMediaSource()
    {
        InitWebSurface();
    }

    private void InitWebSurface()
    {
        WebSurface = Game.CreateWebSurface();
        WebSurface.Size = new Vector2(1600, 900);
        WebSurface.InBackgroundMode = false;
        WebSurface.OnTexture = OnBrowserDataChanged;

        WebSurface.Url = "https://www.youtube.com/embed/XkfmrXLxaNk?autoplay=0;frameborder=0";
    }
    void ResetWebPanel()
    {
        WebSurface.Url = "https://www.youtube.com/embed/XkfmrXLxaNk?autoplay=0;frameborder=0";
    }

    public void SetUrl(string url)
    {
        WebSurface.Url = url;
    }

    public override void OnHotloaded()
    {
        ResetWebPanel();
    }
    private void UpdateWebTexture(ReadOnlySpan<byte> span, Vector2 size)
    {
        if (WebTexture == null || WebTexture.Size != size)
        {
            WebTexture?.Dispose();
            WebTexture = null;
            WebTexture = Texture.Create((int)size.x, (int)size.y, ImageFormat.BGRA8888)
                .WithDynamicUsage()
                .WithName("Web")
                .Finish();

            Style.SetBackgroundImage(WebTexture);
        }
        WebTexture.Update(span, 0, 0, (int)size.x, (int)size.y);
    }
    void OnBrowserDataChanged(ReadOnlySpan<byte> span, Vector2 size)
    {
        if (Game.IsServer)
        {
            return;
        }

        UpdateWebTexture(span, size);
    }
    public override void OnDeleted()
    {
        base.OnDeleted();

        WebTexture?.Dispose();
        WebTexture = null;

        WebSurface?.Dispose();
    }
}
```

### Expected behavior

No errors, the websurface works.

**Comment by Remscar** [comment]
Thanks Garry!
