### ISSUE TITLE
[Asset.Party] Clicking on any link throws Blazor error "Error: System.InvalidOperationException: More than one sibling of component 'Sandbox.Components.Package.PackageCard' has the same key value, 'creation.zojima'. Key values must be unique."

### ISSUE THREAD

**Issue by LiminalCrab** [sboxgame/issues#3566]
### Describe the bug

I originally believed this to just be a Firefox issue, so I ignored it for a time. I tried it on Chrome recently and received the same error. 

Each time I click a link, I get the error below, the page does not redirect. The only way I can change pages it by opening it in a new tab. 

I've cleared my cache multiple times, I've tried separate browsers, I've restarted my computer, I've disabled addons for all browsers. No dice.

#### Chrome
```js
blazor.server.js:1 [2023-07-07T14:34:57.849Z] Error: System.InvalidOperationException: More than one sibling of component 'Sandbox.Components.Package.PackageCard' has the same key value, 'creation.zojima'. Key values must be unique.
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ThrowExceptionForDuplicateKey(Object key, RenderTreeFrame& frame)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.BuildKeyToInfoLookup(DiffContext diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
log @ blazor.server.js:1
pr @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
_invokeClientMethod @ blazor.server.js:1
_processIncomingData @ blazor.server.js:1
Ft.connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
blazor.server.js:1 [2023-07-07T14:34:57.849Z] Information: Connection disconnected.
blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at Nt.send (blazor.server.js:1:54583)
    at Ft._sendMessage (blazor.server.js:1:71306)
    at Ft._sendWithProtocol (blazor.server.js:1:71347)
    at Ft.send (blazor.server.js:1:71455)
    at Object.endInvokeJSFromDotNet (blazor.server.js:1:134987)
    at blazor.server.js:1:3573
send @ blazor.server.js:1
_sendMessage @ blazor.server.js:1
_sendWithProtocol @ blazor.server.js:1
send @ blazor.server.js:1
endInvokeJSFromDotNet @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.server.js:1
_invokeClientMethod @ blazor.server.js:1
_processIncomingData @ blazor.server.js:1
Ft.connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
2blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at Nt.send (blazor.server.js:1:54583)
    at Ft._sendMessage (blazor.server.js:1:71306)
    at Ft._sendWithProtocol (blazor.server.js:1:71347)
    at Ft.send (blazor.server.js:1:71455)
    at Object.beginInvokeDotNetFromJS (blazor.server.js:1:134889)
    at w (blazor.server.js:1:2167)
    at C.invokeMethodAsync (blazor.server.js:1:4035)
    at blazor.server.js:1:11583
    at T (blazor.server.js:1:11761)
    at I (blazor.server.js:1:11552)
```

#### Firefox
```js
[2023-07-07T14:24:16.381Z] Error: System.InvalidOperationException: More than one sibling of component 'Sandbox.Components.Package.PackageCard' has the same key value, 'creation.zojima'. Key values must be unique.

   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ThrowExceptionForDuplicateKey(Object key, RenderTreeFrame& frame)

   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.BuildKeyToInfoLookup(DiffContext diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)

   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)

   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)

   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)

   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)

   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)

   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)

   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)

   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)

   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue() [blazor.server.js:1:119211](https://asset.party/_framework/blazor.server.js)
    log https://asset.party/_framework/blazor.server.js:1
    pr https://asset.party/_framework/blazor.server.js:1
    dr https://asset.party/_framework/blazor.server.js:1
    _invokeClientMethod https://asset.party/_framework/blazor.server.js:1
    _processIncomingData https://asset.party/_framework/blazor.server.js:1
    onreceive https://asset.party/_framework/blazor.server.js:1
    onmessage https://asset.party/_framework/blazor.server.js:1
[2023-07-07T14:24:16.382Z] Information: Connection disconnected. [blazor.server.js:1:39828](https://asset.party/_framework/blazor.server.js)
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    send https://asset.party/_framework/blazor.server.js:1
    _sendMessage https://asset.party/_framework/blazor.server.js:1
    _sendWithProtocol https://asset.party/_framework/blazor.server.js:1
    send https://asset.party/_framework/blazor.server.js:1
    endInvokeJSFromDotNet https://asset.party/_framework/blazor.server.js:1
    beginInvokeJSFromDotNet https://asset.party/_framework/blazor.server.js:1
[blazor.server.js:1:54583](https://asset.party/_framework/blazor.server.js)
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    send https://asset.party/_framework/blazor.server.js:1
    _sendMessage https://asset.party/_framework/blazor.server.js:1
    _sendWithProtocol https://asset.party/_framework/blazor.server.js:1
    send https://asset.party/_framework/blazor.server.js:1
    beginInvokeDotNetFromJS https://asset.party/_framework/blazor.server.js:1
    w https://asset.party/_framework/blazor.server.js:1
    invokeMethodAsync https://asset.party/_framework/blazor.server.js:1
    I https://asset.party/_framework/blazor.server.js:1
    T https://asset.party/_framework/blazor.server.js:1
    I https://asset.party/_framework/blazor.server.js:1
    dispatchGlobalEventToAllElements https://asset.party/_framework/blazor.server.js:1
    onGlobalEvent https://asset.party/_framework/blazor.server.js:1
43 [blazor.server.js:1:54583](https://asset.party/_framework/blazor.server.js)
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    send https://asset.party/_framework/blazor.server.js:1
    _sendMessage https://asset.party/_framework/blazor.server.js:1
    _sendWithProtocol https://asset.party/_framework/blazor.server.js:1
    send https://asset.party/_framework/blazor.server.js:1
    ur https://asset.party/_framework/blazor.server.js:1
    De https://asset.party/_framework/blazor.server.js:1
    Ie https://asset.party/_framework/blazor.server.js:1
    se https://asset.party/_framework/blazor.server.js:1
    onGlobalEvent https://asset.party/_framework/blazor.server.js:1
    onGlobalEvent https://asset.party/_framework/blazor.server.js:1
[blazor.server.js:1:54583](https://asset.party/_framework/blazor.server.js)
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    send https://asset.party/_framework/blazor.server.js:1
    _sendMessage https://asset.party/_framework/blazor.server.js:1
    _sendWithProtocol https://asset.party/_framework/blazor.server.js:1
    send https://asset.party/_framework/blazor.server.js:1
    beginInvokeDotNetFromJS https://asset.party/_framework/blazor.server.js:1
    w https://asset.party/_framework/blazor.server.js:1
    invokeMethodAsync https://asset.party/_framework/blazor.server.js:1
    I https://asset.party/_framework/blazor.server.js:1
    T https://asset.party/_framework/blazor.server.js:1
    I https://asset.party/_framework/blazor.server.js:1
    dispatchGlobalEventToAllElements https://asset.party/_framework/blazor.server.js:1
    onGlobalEvent https://asset.party/_framework/blazor.server.js:1
23 [blazor.server.js:1:54583](https://asset.party/_framework/blazor.server.js)
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    send https://asset.party/_framework/blazor.server.js:1
    _sendMessage https://asset.party/_framework/blazor.server.js:1
    _sendWithProtocol https://asset.party/_framework/blazor.server.js:1
    send https://asset.party/_framework/blazor.server.js:1
    ur https://asset.party/_framework/blazor.server.js:1
    De https://asset.party/_framework/blazor.server.js:1
    Ie https://asset.party/_framework/blazor.server.js:1
    se https://asset.party/_framework/blazor.server.js:1
    onGlobalEvent https://asset.party/_framework/blazor.server.js:1
    onGlobalEvent https://asset.party/_framework/blazor.server.js:1
[blazor.server.js:1:54583](https://asset.party/_framework/blazor.server.js)
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    send https://asset.party/_framework/blazor.server.js:1
    _sendMessage https://asset.party/_framework/blazor.server.js:1
    _sendWithProtocol https://asset.party/_framework/blazor.server.js:1
    send https://asset.party/_framework/blazor.server.js:1
    beginInvokeDotNetFromJS https://asset.party/_framework/blazor.server.js:1
    w https://asset.party/_framework/blazor.server.js:1
    invokeMethodAsync https://asset.party/_framework/blazor.server.js:1
    I https://asset.party/_framework/blazor.server.js:1
    T https://asset.party/_framework/blazor.server.js:1
    I https://asset.party/_framework/blazor.server.js:1
    dispatchGlobalEventToAllElements https://asset.party/_framework/blazor.server.js:1
    onGlobalEvent https://asset.party/_framework/blazor.server.js:1
43 [blazor.server.js:1:54583](https://asset.party/_framework/blazor.server.js)
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    send https://asset.party/_framework/blazor.server.js:1
    _sendMessage https://asset.party/_framework/blazor.server.js:1
    _sendWithProtocol https://asset.party/_framework/blazor.server.js:1
    send https://asset.party/_framework/blazor.server.js:1
    ur https://asset.party/_framework/blazor.server.js:1
    De https://asset.party/_framework/blazor.server.js:1
    Ie https://asset.party/_framework/blazor.server.js:1
    se https://asset.party/_framework/blazor.server.js:1
    onGlobalEvent https://asset.party/_framework/blazor.server.js:1
    onGlobalEvent https://asset.party/_framework/blazor.server.js:1
[blazor.server.js:1:54583](https://asset.party/_framework/blazor.server.js)
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    send https://asset.party/_framework/blazor.server.js:1
    _sendMessage https://asset.party/_framework/blazor.server.js:1
    _sendWithProtocol https://asset.party/_framework/blazor.server.js:1
    send https://asset.party/_framework/blazor.server.js:1
    beginInvokeDotNetFromJS https://asset.party/_framework/blazor.server.js:1
    w https://asset.party/_framework/blazor.server.js:1
    invokeMethodAsync https://asset.party/_framework/blazor.server.js:1
    I https://asset.party/_framework/blazor.server.js:1
    T https://asset.party/_framework/blazor.server.js:1
    I https://asset.party/_framework/blazor.server.js:1
    dispatchGlobalEventToAllElements https://asset.party/_framework/blazor.server.js:1
    onGlobalEvent https://asset.party/_framework/blazor.server.js:1
2 [blazor.server.js:1:54583](https://asset.party/_framework/blazor.server.js)
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. [css2:78:27](https://fonts.googleapis.com/css2?family=Poppins&family=Sen:wght@400;700&family=Material+Icons)
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. [editor.main.css:6:4839](https://asset.party/_content/Facepunch.Components.BlockEd.CodeBlock/lib/monaco/min/vs/editor/editor.main.css)
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. [editor.main.css:6:10943](https://asset.party/_content/Facepunch.Components.BlockEd.CodeBlock/lib/monaco/min/vs/editor/editor.main.css)
Error in parsing value for ‘outline’.  Declaration dropped. [editor.main.css:6:21362](https://asset.party/_content/Facepunch.Components.BlockEd.CodeBlock/lib/monaco/min/vs/editor/editor.main.css)
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. [editor.main.css:6:40667](https://asset.party/_content/Facepunch.Components.BlockEd.CodeBlock/lib/monaco/min/vs/editor/editor.main.css)
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. [editor.main.css:6:40816](https://asset.party/_content/Facepunch.Components.BlockEd.CodeBlock/lib/monaco/min/vs/editor/editor.main.css)
Error in parsing value for ‘outline’.  Declaration dropped. [editor.main.css:6:50691](https://asset.party/_content/Facepunch.Components.BlockEd.CodeBlock/lib/monaco/min/vs/editor/editor.main.css)
Error in parsing value for ‘animation-duration’.  Declaration dropped. [editor.main.css:6:53957](https://asset.party/_content/Facepunch.Components.BlockEd.CodeBlock/lib/monaco/min/vs/editor/editor.main.css)
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    send https://asset.party/_framework/blazor.server.js:1
    _sendMessage https://asset.party/_framework/blazor.server.js:1
    _sendWithProtocol https://asset.party/_framework/blazor.server.js:1
    send https://asset.party/_framework/blazor.server.js:1
    beginInvokeDotNetFromJS https://asset.party/_framework/blazor.server.js:1
    w https://asset.party/_framework/blazor.server.js:1
    invokeMethodAsync https://asset.party/_framework/blazor.server.js:1
    I https://asset.party/_framework/blazor.server.js:1
    T https://asset.party/_framework/blazor.server.js:1
    I https://asset.party/_framework/blazor.server.js:1
    dispatchGlobalEventToAllElements https://asset.party/_framework/blazor.server.js:1
    onGlobalEvent https://asset.party/_framework/blazor.server.js:1
```

### To Reproduce

1. Log into Asset.Party
2. Click on any link.

### Expected behavior

The links should redirect to their corresponding webpage.

**Comment by garrynewman** [comment]
Thanks - this should be fixed now
