### ISSUE TITLE
Game doesnt launch (black screen) if it cannot connect to facepunch

### ISSUE THREAD

**Issue by dm4uz3** [sboxgame/issues#3610]
### Describe the bug

I tried to open the game with my VPN still on and it was blocked by facepunch's servers so all I got was a black screen. 

### To Reproduce

open s&box

### Expected behavior

it works. or at least some user readable error message 

### Media/Files

![image](https://github.com/sboxgame/issues/assets/19360280/3f165d45-84f4-41d2-8c0b-79899f361963)

### Additional context

log goes like this 
```
--- End of stack trace from previous location ---
   at Sandbox.Api.PostAsync(String url, Object values, Dictionary`2 headers, Callback progress, CancellationToken token)
2023/07/13 18:06:50.4488	Generic	No account information - retrying..	
2023/07/13 18:06:52.8049	Generic	Exception when posting to API	System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions. (sap.facepunch.com:443)
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
```

full thing attached here 
[Log.1.log](https://github.com/sboxgame/issues/files/12041997/Log.1.log)

**Comment by handsomematt** [comment]
#2743
