### ISSUE TITLE
String errors showing up breaking things

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#3866]
### Describe the bug

Today these randomly started appearing, worked fine yesterday:

### When loading a map
`Interop ToType - need to add the ability to change from string to Sandbox.FGDCurve`
```
ToType - need to add the ability to change from string to Sandbox.FGDCurve
System.Exception: ToType - need to add the ability to change from string to Sandbox.FGDCurve
   at Sandbox.SandboxSystemExtensions.ToType(String str, Type t)
   at Sandbox.Entity.InternalEntityKeyValue(UInt32 nameToken, String value, Int32 type)
   at Managed.SourceServer.Exports.Sandbox_Entity_InternalEntityKeyValue(UInt32 self, UInt32 nameToken, IntPtr value, Int32 type)
```

### When sending a ClientRPC message
`Interop Can not NetWrite type String as it is or contains reference types`
```
Can not NetWrite type String as it is or contains reference types
System.Exception: Can not NetWrite type String as it is or contains reference types
   at Sandbox.NetWrite.Write[T](T[] val)
   at StrikeForce.HUD.AddToExperienceDisplay__RpcProxy(Int32 exp, String[] infoLabels, Nullable`1 toTarget) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\sbox-strikeforce\code\base\HUD.cs:line 333
```

**Comment by handsomematt** [comment]
These should be fixed now, there could be other ToType types that error but I've not come across any.

**Comment by timmybo5** [comment]
Everything works how it should, huge thanks you saved the playtest!
