### ISSUE TITLE
Character freezes, not able to move, use tools, use noclip. 

### ISSUE THREAD

**Issue by theWildRaptor** [sboxgame/issues#3886]
### Describe the bug

I created a custom game with up to 12 player slots on a map Flat grass by Facepunch. However when I tried to spawn an entity my character freezes and can't move, can't move objects with the physgun, also can't use noclip. However you can shoot RAPIDLY and use the fists to punch 100x. I have to restart the game. I tried with different entities and still the same issue.

### To Reproduce

I created a video replicating the issue.
Step 1: Launch Sandbox
Step 2: Create a game with 12 slots on a map Flat grass by Facepunch
Step 3: Try spawning an entity.
Step 4: Your character should freeze and can't do anything.

### Expected behavior

Character should be free to move and use the physgun.

### Media/Files

[https://www.youtube.com/watch?v=nq87dMl2L3g](Youtube Link)

**Comment by rentusik** [comment]
have the same issue on construct with 1/8 players

**Comment by rentusik** [comment]
> have the same issue on construct with 1/8 players

but i can't even shoot and spawn things.

**Comment by handsomematt** [comment]
What does the error say? Post your Log.txt file from the logs folder

**Comment by rentusik** [comment]
> What does the error say? Post your Log.txt file from the logs folder

i can give u mine 
[Log.log](https://github.com/sboxgame/issues/files/12403113/Log.log)

**Comment by rentusik** [comment]
now i have steam cloud error :D

**Comment by rentusik** [comment]
> ### Describe the bug
> I created a custom game with up to 12 player slots on a map Flat grass by Facepunch. However when I tried to spawn an entity my character freezes and can't move, can't move objects with the physgun, also can't use noclip. However you can shoot RAPIDLY and use the fists to punch 100x. I have to restart the game. I tried with different entities and still the same issue.
> 
> ### To Reproduce
> I created a video replicating the issue. Step 1: Launch Sandbox Step 2: Create a game with 12 slots on a map Flat grass by Facepunch Step 3: Try spawning an entity. Step 4: Your character should freeze and can't do anything.
> 
> ### Expected behavior
> Character should be free to move and use the physgun.
> 
> ### Media/Files
> [https://www.youtube.com/watch?v=nq87dMl2L3g](Youtube Link)
> 
> ### Additional context
> _No response_

LMAO thanks bro, close and open the game works

**Comment by theWildRaptor** [comment]
This is my log file. I had the game fully closed and it fixed the issue. 
[Log.4.log](https://github.com/sboxgame/issues/files/12403130/Log.4.log)

**Comment by handsomematt** [comment]
```
2023/08/22 00:51:56.6974    Interop    Object reference not set to an instance of an object.    System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.ManagedInputs.ReadInputProperties(BinaryReader reader, Object target)
   at Sandbox.ManagedInputs.Process(IClient client, CUserCmd cmd)
   at Sandbox.PlayerCommand.Run(IClient cl, CUserCmd& cmd)
   at Sandbox.PlayerCommand.RunServer(IClient player, CUserCmd& cmd)
   at Managed.SourceServer.Exports.Sandbox_PlayerCommand_RunServer(UInt32 player, IntPtr cmd)
```

Looks like the error, could you take a look @kurozael ?

**Comment by kurozael** [comment]
Yep I'll get it sorted 👍

**Comment by kurozael** [comment]
Seems to be a bunch of other errors as well, maybe types are being mismatched somehow:

```
2023/08/22 00:51:48.9343	Server	Error calling event 'server.tick' on 'GlassShard 187'	System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Sandbox.Internal.EventSystem.<>c__DisplayClass10_0.<BuildDelegate>b__0(Object o, Object[] p)
   at Sandbox.Internal.EventSystem.Run(String v)
2023/08/22 00:51:49.0711	Server	Error calling event 'physics.prestep' on 'GravGun 195'	System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Sandbox.Internal.EventSystem.<>c__DisplayClass10_0.<BuildDelegate>b__0(Object o, Object[] p)
   at Sandbox.Internal.EventSystem.Run(String v)
2023/08/22 00:51:49.0711	Server	Error calling event 'physics.prestep' on 'PhysGun 194'	System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Sandbox.Internal.EventSystem.<>c__DisplayClass10_0.<BuildDelegate>b__0(Object o, Object[] p)
   at Sandbox.Internal.EventSystem.Run(String v)
2023/08/22 00:51:49.0711	Server	Error calling event 'server.tick' on 'GlassShard 188'	System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Sandbox.Internal.EventSystem.<>c__DisplayClass10_0.<BuildDelegate>b__0(Object o, Object[] p)
   at Sandbox.Internal.EventSystem.Run(String v)
```

**Comment by kurozael** [comment]
Did you say you were using custom game code or just loading Sandbox from Asset Party?

**Comment by theWildRaptor** [comment]
I was able to replicate it with the latest update a couple of times, you did fix a bunch of things, I have them mentioned in the video. I'm uploading the LOG file from the video as well. https://www.youtube.com/watch?v=wScPLCFpfLE
[Log.11.log](https://github.com/sboxgame/issues/files/12408426/Log.11.log)

**Comment by theWildRaptor** [comment]
Wrong LOG file* This is the correct LOG coresponding to the video
[Log.13.log](https://github.com/sboxgame/issues/files/12409635/Log.13.log)

**Comment by Metapyziks** [comment]
Those reproduction steps are perfect, thank you!

**Comment by Metapyziks** [comment]
Reduced the repro steps down to:
* Select TFS2 in game list
* Minimize or close
* Select Sandbox in game list
* `> map facepunch.flatgrass`
* `> spawnpackage bnka.garry_cube`
* `> map facepunch.flatgrass`
* `> spawnpackage bnka.garry_cube`
* Error spam

**Comment by Metapyziks** [comment]
When selecting TFS2 beforehand, the second spawn of Garry Cube causes this:
```
Server	RegisterAssembly( package.base@0.0.352.0, package.base@0.0.352.0 )	
Server	RegisterAssembly( package.facepunch.sandbox@0.0.353.0, package.facepunch.sandbox@0.0.353.0 )	
```

**Comment by Metapyziks** [comment]
I've got a fix, just want to test it a bit more first before merging.
