### ISSUE TITLE
Package.MountAsync sometimes causes an error.

### ISSUE THREAD

**Issue by AncientEntity** [sboxgame/issues#3928]
### Describe the bug

I'm working with "Package.MountAsync" and it runs it on an addon startup to mount some other addons. Rarely on startup I get 2 errors to the console, so I assume it's a race condition or communication error with asset.party.

Error 1:
```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Value cannot be null. (Parameter 'source'))
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Sandbox.Package.Download(String absoluteLocation, ILoadingInterface loader, PackageDownloadMode downloadMode, CancellationToken token)
   at Sandbox.PackageManager.ActivePackage.DownloadAsync(ILoadingInterface loader, PackageDownloadMode downloadMode, CancellationToken token)
   at Sandbox.PackageManager.ActivePackage.Create(Package package, ILoadingInterface loader, PackageDownloadMode downloadMode, CancellationToken token)
   at Sandbox.PackageManager.InstallAsync(String packageIdent, String contextTag, CancellationToken token, Nullable`1 options)
   at Sandbox.PackageManager.InstallDependencies(Package package, String contextTag, CancellationToken token, Nullable`1 options)
   at Sandbox.PackageManager.InstallAsync(String packageIdent, String contextTag, CancellationToken token, Nullable`1 options)
   at Sandbox.GameMenu.GameMenuInstance.LoadAsync(CancellationToken token)
   at Sandbox.GameMenu.GameMenuDll.LoadAsync(IPanel parent, String ident, Boolean reload, CancellationToken ct)

```
Error 2:
```
Value cannot be null. (Parameter 'source')
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Sandbox.Package.Download(String absoluteLocation, ILoadingInterface loader, PackageDownloadMode downloadMode, CancellationToken token)
   at Sandbox.PackageManager.ActivePackage.DownloadAsync(ILoadingInterface loader, PackageDownloadMode downloadMode, CancellationToken token)
   at Sandbox.PackageManager.ActivePackage.Create(Package package, ILoadingInterface loader, PackageDownloadMode downloadMode, CancellationToken token)
   at Sandbox.PackageManager.InstallAsync(String packageIdent, String contextTag, CancellationToken token, Nullable`1 options)
   at Sandbox.PackageManager.InstallDependencies(Package package, String contextTag, CancellationToken token, Nullable`1 options)
   at Sandbox.PackageManager.InstallAsync(String packageIdent, String contextTag, CancellationToken token, Nullable`1 options)
   at Sandbox.GameMenu.GameMenuInstance.LoadAsync(CancellationToken token)
   at Sandbox.GameMenu.GameMenuDll.LoadAsync(IPanel parent, String ident, Boolean reload, CancellationToken ct)

```

they happen together one after the other.

### To Reproduce

1. Inside of an addon get a package with FetchAsync.
2. With the gotten package do Package.MountAsync
3. It occasionally will happen

### Expected behavior

Maybe MountAsync should return more info? I guess expected behaviour is communicating that there was an error mounting.

### Additional context

It's with the ryan.adminessentials addon. Repo not public although if FP wants to see it I'm down to giving access for the greater good <3

**Comment by AncientEntity** [comment]
To note it doesn't always happen and I check to see if Package is valid and such before attempting to run MountAsync.
