### ISSUE TITLE
Duplication of panels implementing ILoadingScreenPanel 

### ISSUE THREAD

**Issue by Cryotheus** [sboxgame/issues#4029]
### Describe the bug

LoadingScreen panel is not cleaned up after closing the project's main menu, under certain conditions with hotloading.

### To Reproduce

1. Open a game project
2. Close the project's main menu
3. Re-open the main menu using the blu play button next to the selected load configuration
4. Click the *test loading screen* button
5. Add a new div to the .razor file that implements `Sandbox.Menu.ILoadingScreenPanel`
6. Error 1, 2, or both will appear
7. Click the *test loading screen* button until the loading screen re-appears
8. Close the project's main menu by clicking the *X button* on the top-right
Repeating these steps will create another one

### Expected behavior

The LoadingScreen should be removed when the project's main menu is closed

### Media/Files

| Normal | Broken |
| --- | --- |
| <img src=https://github.com/sboxgame/issues/assets/14439112/0dee8fe6-6431-458c-9af8-03268fa50bd3 width=350px > | <img src=https://github.com/sboxgame/issues/assets/14439112/bcbc3d1b-566b-4b52-8c5d-21d9ec4837c3 width=350px > |
| <img src=https://github.com/sboxgame/issues/assets/14439112/8c1148a2-c195-45a4-bee4-bab55fa65ba5 width=350px > | <img src=https://github.com/sboxgame/issues/assets/14439112/e8c79a7a-798c-4883-8a75-bcb16441ba60 width=350px > |

### Error 1
```
Assert: False
  Member: System.Collections.Generic.Dictionary<System.String, Sandbox.TypeDescription>.Dictionary`2 (System.Private.CoreLib)
  Path: [(package.bugreportorg.bugreportpackage v0.0.110.0) BugReportUI.MainMenu::ActiveMainMenu].destinations
System.Exception: Assert: False
   at Sandbox.Diagnostics.Assert.False(Boolean isValid, String message)
   at Sandbox.Internal.TypeDescriptionUpgrader.OnTryCreateNewInstance(Object oldInstance, Object& newInstance)
   at Sandbox.Hotload.InstanceUpgrader.TryCreateNewInstance(Object oldInstance, Object& newInstance)
   at Sandbox.Upgraders.UpgraderGroup.TryCreateNewInstance(Object oldInstance, Object& newInstance)
   at Sandbox.Hotload.GetNewInstance(Object oldInstance)
   at Sandbox.Hotload.InstanceUpgrader.GetNewInstance(Object oldInstance)
   at Sandbox.Upgraders.SpecialCases.DictionaryUpgrader.OnProcessInstance(Object oldInstance, Object newInstance)
   at Sandbox.Hotload.InstanceUpgrader.ProcessInstance(Object oldInstance, Object newInstance)
```
### Error 2
```
Couldn't resolve 'package.bugreportorg.bugreportpackage, Version=0.0.110.0, Culture=neutral, PublicKeyToken=null' []
  Member: System.Collections.Generic.Dictionary<System.String, System.Func<System.Boolean>>.Dictionary`2 (System.Private.CoreLib)
  Path: [(package.bugreportorg.bugreportpackage v0.0.110.0) BugReportUI.MainMenu::ActiveMainMenu].classBinds
System.Exception: Couldn't resolve 'package.bugreportorg.bugreportpackage, Version=0.0.110.0, Culture=neutral, PublicKeyToken=null' []
   at Sandbox.AccessControl.Resolve(AssemblyNameReference name)
   at Sandbox.Hotload.GetAssemblyDefinition(Assembly asm)
   at Sandbox.Hotload.GetTypeDefinition(Type type)
   at Sandbox.Hotload.GetMethodDefinition(MethodBase method)
   at Sandbox.Hotload.GetScopeMethodOrdinal(MethodBase scopeMethod)
   at Sandbox.Hotload.FindScopeMethod(Type declaringType, String scopeMethodName, Int32 scopeMethodOrdinal)
   at Sandbox.Hotload.InstanceUpgrader.FindScopeMethod(Type declaringType, String scopeMethodName, Int32 scopeMethodOrdinal)
   at Sandbox.Upgraders.DelegateUpgrader.GetMatchingLambdaMethod(MethodInfo oldLambda, Type oldDeclaringType, LambdaMethodName oldName, Type newDeclaringType)
   at Sandbox.Upgraders.DelegateUpgrader.GetMatchingLambdaMethod(MethodInfo oldMethod)
   at Sandbox.Upgraders.DelegateUpgrader.OnTryCreateNewInstance(Object oldInstance, Object& newInstance)
   at Sandbox.Hotload.InstanceUpgrader.TryCreateNewInstance(Object oldInstance, Object& newInstance)
   at Sandbox.Upgraders.UpgraderGroup.TryCreateNewInstance(Object oldInstance, Object& newInstance)
   at Sandbox.Hotload.GetNewInstance(Object oldInstance)
   at Sandbox.Hotload.InstanceUpgrader.GetNewInstance(Object oldInstance)
   at Sandbox.Upgraders.SpecialCases.DictionaryUpgrader.OnProcessInstance(Object oldInstance, Object newInstance)
   at Sandbox.Hotload.InstanceUpgrader.ProcessInstance(Object oldInstance, Object newInstance)
```

**Comment by Cryotheus** [comment]
Not sure when this was fixed, but the issue is no longer present.
