### ISSUE TITLE
Restarting a game / Hotloading will break TypeLibrary

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#4067]
### Describe the bug

I have this debug command called set_state where I can write "set_state play/score/tutorial" etc... and it will run the static SetState<T> method, with T being a GameState class.
After restarting my game or hotloading, the console command stops working, this forces me to restart S&box.
Here's the errors: 
![image](https://github.com/sboxgame/issues/assets/59583743/c9077e65-2981-4d98-bc11-86a6613ecca5)

```
Exception when calling command "set_state"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BombSurvival.BombSurvival.SetState[T]() in C:\Users\uberm\Desktop\Addons\bomb_survival\code\GameStates\BombSurvival.GameState.cs:line 27
   at BombSurvival.BombSurvival.SetState(String state) in C:\Users\uberm\Desktop\Addons\bomb_survival\code\BombSurvival.Debug.cs:line 25
   at InvokeStub_BombSurvival.SetState(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
```
Unknown Type -1
   at Sandbox.Internal.TypeLibrary.Create[T](Int32 ident)
   at Sandbox.EntityManager.CreateClientsideOfNetworkedEntity(C_BaseEntity baseEnt, Int32 managedClassIdent)
   at Managed.SourceClient.Exports.Sandbox_EntityManager_CreateClientsideOfNetworkedEntity(IntPtr instance, Int32 managedClassIdent)
   at NativeEngine.EngineGlobal.SourceEngineFrame(CMaterialSystem2AppSystemDict appDict, Double currentTime, Double previousTime)
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
   at Sandbox.SourceEngineApp.RunFrame() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 46
   at Sandbox.SourceEngineApp.RunLoop() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 37
   at Sandbox.Program.LaunchGame() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 108
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 58
```
```
Unknown entity with id 118 (native class is baseentity). This indicates that we're not running the same code as the server.
System.Exception: Unknown entity with id 118 (native class is baseentity). This indicates that we're not running the same code as the server.
   at Sandbox.EntityManager.CreateClientsideOfNetworkedEntity(C_BaseEntity baseEnt, Int32 managedClassIdent)
   at Managed.SourceClient.Exports.Sandbox_EntityManager_CreateClientsideOfNetworkedEntity(IntPtr instance, Int32 managedClassIdent)

```

This is where we're calling the console command:
https://github.com/Small-Fish-Dev/Bomb-Survival/blob/9c671a8679f3853786d92a6e1b48ec9e7e5ca293/code/BombSurvival.Debug.cs#L14C41-L14C41

This is the GameState class:
https://github.com/Small-Fish-Dev/Bomb-Survival/blob/main/code/GameStates/BombSurvival.GameState.cs

And this is where it's handled:
https://github.com/Small-Fish-Dev/Bomb-Survival/blob/9c671a8679f3853786d92a6e1b48ec9e7e5ca293/code/GameStates/BombSurvival.GameState.cs#L21

It seems to be erroring at `Activator.CreateInstance<T>();`

### To Reproduce

1. Clone this repo: https://github.com/Small-Fish-Dev/Bomb-Survival (Or just start directly the game fish.bomb_survival It's hidden but updated, just unsure if this happens on the live version)
2. Start the game (Through launcher or game menu)
3. Type "set_state tutorial" in the console (First time it works)
4. Hotload or restart the game
5. Type "set_state tutorial" again

Should give you the error

### Additional context

Might be related to https://github.com/sboxgame/issues/issues/4066

**Comment by Metapyziks** [comment]
There were some hotload fixes in the last day or so, can you still reproduce this issue?

**Comment by yuberee** [comment]
Yup still happens.

**Comment by Metapyziks** [comment]
Weird, I'll see what's different about my setup.

**Comment by Metapyziks** [comment]
Seems like console commands weren't getting removed when leaving a game. Should be fixed on staging now, but let me know if it's still an issue.

**Comment by yuberee** [comment]
Works now!
