### ISSUE TITLE
Game project fails to load GameMenu

### ISSUE THREAD

**Issue by timmybo5** [sboxgame/issues#4068]
### Describe the bug

I've tried to load a few gamemodes without custom menu and none of them work being stuck at the black screen menu, please fix this as we are unable to develop anything.

This used to work fine a couple days ago.

![image](https://github.com/sboxgame/issues/assets/4988198/5a99eab9-a077-41f2-a3f4-bafd3668c93c)

```
Couldn't find menu in [package.strikeforce.strikeforce] - using fallback
   at Sandbox.GameMenu.GameMenuInstance.CreatePanels(Enroller enroller)
   at Sandbox.GameMenu.GameMenuInstance.GameStartup(Enroller enroller)
   at Sandbox.GameMenu.GameMenuDll.LoadAsync(IPanel parent, String ident, Boolean reload, CancellationToken ct)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at Sandbox.Tasks.ExpirableSynchronizationContext.ProcessQueue()
   at Sandbox.EngineLoop.FrameStart()
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
   at Sandbox.SourceEngineApp.RunFrame() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 46
   at Sandbox.SourceEngineApp.RunLoop() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 37
   at Sandbox.Program.LaunchGame() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 108
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 58
```

### Sometimes when backing out the black menu and trying again it gives an error:

![image](https://github.com/sboxgame/issues/assets/4988198/0113de03-be36-486c-8c5d-8b07de5fe13d)

```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (LoadPackage: Couldn't find active package 'local.base')
System.Exception: LoadPackage: Couldn't find active package 'local.base'
   at Sandbox.PackageLoader.LoadPackage(String ident, PackageDownloadMode downloadMode, Boolean exactName)
   at Sandbox.PackageLoader.Enroller.LoadPackage(String packageName, PackageDownloadMode mode)
   at Sandbox.GameMenu.GameMenuInstance.CreatePanels(Enroller enroller)
   at Sandbox.GameMenu.GameMenuInstance.GameStartup(Enroller enroller)
   at Sandbox.GameMenu.GameMenuDll.LoadAsync(IPanel parent, String ident, Boolean reload, CancellationToken ct)
```

### To Reproduce

Load a game that doesn't have a custom menu defined, tool mode or normal doesn't matter.
For example: `swb.demo`

### Expected behavior

It shows the default fallback menu if no custom menu is provided

**Comment by DevulTj** [comment]
This appears to occur when the ident has a dot in it.

**Comment by DevulTj** [comment]
Actually I'm full of shit - a dot will break it, but you don't have one here

**Comment by dictateurfou** [comment]
I have had this problem for a long time

**Comment by realEpiK** [comment]
i agree

**Comment by Captianfrost15** [comment]
i have this problem currently, and i am trying to find the way to fix it

**Comment by AfteraOfficiel** [comment]
Same problem here :/

**Comment by frn1** [comment]
I'm getting the exact same error, please fix it as soon as possible!

**Comment by timmybo5** [comment]
This seems to be fixed, thanks! :D
