### ISSUE TITLE
Hotreload is Bugged

### ISSUE THREAD

**Issue by Andrei15193** [sboxgame/issues#4125]
### Describe the bug

Whenever making a change, the Sbox Editor hits an error that it cannot get out of. It continually log the description for null reference exception.

Log snapshot:
```log
 09:06:23   hotload/GameMenu Assert: True
 09:06:32   Interop Removed Child but didn't have child!
 09:07:50   Interop  [3,928] Object reference not set to an instance of an object.
 09:07:51   hotload/GameMenu Assert: True
 09:10:39   Interop  [4,338] Object reference not set to an instance of an object.
```

### To Reproduce

1. Create a new game project, use the minimal template
2. Open the game project in an IDE (or even file explorer)
3. Change any file to trigger a hotreload

### Expected behavior

The game is reloaded and no error is logged in the console (unless I mess something up).

### Media/Files

It seems that the view menu is also affected, multiple "New Asset Browser" menu items are added when changing a watched file. This happens at random so triggering a reload multiple times may get it to bug.

![image](https://github.com/sboxgame/issues/assets/3336988/76324cd3-59c6-440f-bd1e-3415998b01e8)

Using a custom menu results in the same bug.

Stack trace for `Assert: True`:
```log
Assert: True
  Member: Sandbox.MethodDescription.MethodDescription (Sandbox.Reflection)
  Path: [(Sandbox.Engine) Sandbox.InteropSystem::Objects].Triggered.method.TypeDescription.Members[]
System.Exception: Assert: True
   at Sandbox.Diagnostics.Assert.True(Boolean isValid, String message)
   at Sandbox.Upgraders.DelegateUpgrader.GetLambdaMethodInfo(String lambdaName, String declaringTypeName, Boolean isStatic, LambdaCaptureMode& captureMode, LambdaMethodName& nameInfo)
   at Sandbox.Upgraders.DelegateUpgrader.GetLambdaMethodInfo(MethodInfo lambda, Type& declaringType, LambdaCaptureMode& captureMode, LambdaMethodName& nameInfo)
   at Sandbox.Upgraders.DelegateUpgrader.GetMatchingLambdaMethod(MethodInfo oldMethod)
   at Sandbox.Upgraders.MemberInfoUpgrader.OnTryCreateNewInstance(Object oldInstance, Object& newInstance)
   at Sandbox.Hotload.InstanceUpgrader.TryCreateNewInstance(Object oldInstance, Object& newInstance)
   at Sandbox.Upgraders.UpgraderGroup.TryCreateNewInstance(Object oldInstance, Object& newInstance)
   at Sandbox.Hotload.GetNewInstance(Object oldInstance)
   at Sandbox.Hotload.InstanceUpgrader.GetNewInstance(Object oldInstance)
   at Sandbox.Upgraders.DefaultUpgrader.ProcessFieldValue(Object oldInst, FieldInfo srcField)
   at Sandbox.Upgraders.DefaultUpgrader.ProcessObjectFields(Object oldInst, Object newInst)
   at Sandbox.Upgraders.DefaultUpgrader.OnProcessInstance(Object oldInstance, Object newInstance)
   at Sandbox.Hotload.InstanceUpgrader.ProcessInstance(Object oldInstance, Object newInstance)
```

Stack trace for `Removed Child but didn't have child`
```log
Removed Child but didn't have child!
System.Exception: Removed Child but didn't have child!
   at Sandbox.UI.Panel.RemoveChild(Panel p)
   at Sandbox.UI.Panel.set_Parent(Panel value)
   at Sandbox.UI.Panel.Delete(Boolean immediate)
   at Sandbox.UISystem.RunDeferredDeletion(Boolean force)
   at Sandbox.UISystem.Simulate()
   at Sandbox.MenuDll.SimulateUI()
   at Sandbox.EngineLoop.SimulateUI()
   at Sandbox.EngineLoop.OnClientOutput()
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_OnClientOutput()
```

Stack trace for the null reference exception:
```log
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.UI.YogaWrapper.RemoveChild(YogaWrapper yogaNode)
   at Sandbox.UI.Panel.SortChildrenOrder()
   at Sandbox.UI.Panel.PreLayout(LayoutCascade cascade)
   at Sandbox.UI.Panel.PreLayout(LayoutCascade cascade)
   at Sandbox.UI.Panel.PreLayout(LayoutCascade cascade)
   at Sandbox.UI.RootPanel.PreLayout()
   at Sandbox.UI.RootPanel.PreLayout(Rect screenSize)
   at Sandbox.UISystem.PreLayout()
   at Sandbox.UISystem.Simulate()
   at Sandbox.MenuDll.SimulateUI()
   at Sandbox.EngineLoop.SimulateUI()
   at Sandbox.EngineLoop.OnClientOutput()
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_OnClientOutput()
```

### Additional context

I'm running on Windows 11, verified game files and then also reinstalled. After each step the error persists in the same way.

**Comment by Kolya142** [comment]
i'm running on Windows 10, verified game files and then also reinstalled.
and I'm getting this error

**Comment by LiminalCrab** [comment]
Also receiving persistent errors when attempting to hot reload:


https://gist.github.com/LiminalCrab/1e733e611fae0fc53238e5dcfeb9d3ed

**Comment by Andrei15193** [comment]
Checked with the latest build, the bug does not always reproduce, however I have found a peculiar case for the menu.

If I define a custom menu as a razor page and include a code part, the bug reproduces whenever I make a change in the `@code` part.

Making changes in the HTML part, e.g.: adding more elements or changing the text, works.
```razor
@using Sandbox
@using Sandbox.Menu
@using Sandbox.UI

@inherits NavHostPanel
@implements IGameMenuPanel

<root>
    <div>This is a menu, I promise.</div>
</root>
```

As soon as I add a `@code` part and make changes to that part, the bug happens again even after reloading the editor.

```razor
@using Sandbox
@using Sandbox.Menu
@using Sandbox.UI

@inherits NavHostPanel
@implements IGameMenuPanel

<root>
    <div>This is a menu, I promise.</div>
</root>

@code {
    public Main() {
        Log.Info("Hmm");
    }
}
```

Simply changing the logged message will trigger the bug.

**Comment by LiminalCrab** [comment]
For me, it's occurring after every other hot reload still. Same for Shadowbrain 

@Aleph
Did anyone manage to fix their hot reload yet

ShadowBrain — Today at 9:28 AM
Not everyone has the issue sadly
so no


https://github.com/sboxgame/issues/assets/78995156/aed8e369-e21f-4cb8-9581-2efa39a839dc

**Comment by Metapyziks** [comment]
This fix might only be for one particular error, feel free to re-open if you get more.

**Comment by Andrei15193** [comment]
The issue still reproduces for me for the menu, but I think it may actually be tied to the error message that gets shown.

I get the assert false error and this shows up:
![image](https://github.com/sboxgame/issues/assets/3336988/4632e0f6-1af6-47ec-8729-49e721c8c69d)

It stays like that for a bit, then I get the infinite null reference exception, but the error box instantly looks like this:
![image](https://github.com/sboxgame/issues/assets/3336988/fff402a1-df94-4979-a9c6-00142ed9561d)

**Comment by Andrei15193** [comment]
> The issue still reproduces for me for the menu, but I think it may actually be tied to the error message that gets shown.
> 
> I get the assert false error and this shows up: ![image](https://user-images.githubusercontent.com/3336988/281528855-4632e0f6-1af6-47ec-8729-49e721c8c69d.png)
> 
> It stays like that for a bit, then I get the infinite null reference exception, but the error box instantly looks like this: ![image](https://user-images.githubusercontent.com/3336988/281529152-fff402a1-df94-4979-a9c6-00142ed9561d.png)

Never mind, I was hasty with the check and the build with the fix wasn't available yet.

The issue is fixed for me now, thanks! 👍

**Comment by LiminalCrab** [comment]
No longer receiving assertion, but hot reloading is continuing to crash after 2nd load attempt in any project.

```csharp
01:21:58   engine/Qt invalid splitter encountered
 01:21:20   engine/Engine SteamAPI_Init succeeded.  SteamID is [U:1:13431743] (76561197973697471), AppID is 590830
 01:21:20   engine/Steam CSteam3Client::Activate succeeded.  SteamID is [U:1:13431743] (76561197973697471), AppID is 590830
 01:21:50   engine/ToolsStallMonitor  [1] Stall detected.
 01:22:04   engine/Client CL:  disconnect
 01:22:04   GameMenu Register Assembly: [package.base, Version=0.0.101.0, Culture=neutral, PublicKeyToken=null](arg:0)
 01:22:04   GameMenu Register Assembly: [package.facepunch.testbed, Version=0.0.103.0, Culture=neutral, PublicKeyToken=null](arg:0)
 01:22:04   GameMenu Register Assembly: [package.facepunch.testbed.editor, Version=0.0.107.0, Culture=neutral, PublicKeyToken=null](arg:0)
 01:22:05   Generic Exception waiting for task to finish
 01:22:25   engine/ResourceSystem Error loading resource file "maps/customer_returns01/world_visibility.vvis_c" (Error: ERROR_FILEOPEN: File not found)
 01:22:40   GameMenu  [1] Spawner
 01:22:40   GameMenu Spawner.cs
 01:22:43   GameMenu  [1] Spawner
 01:22:43   GameMenu Spawner.cs
 01:22:45   GameMenu [[GameMenu](arg:0)] Detected Asset File Changed /scenes/customer_returns.scene_c
 01:23:17   GameMenu Unregister Assembly: [package.facepunch.testbed, Version=0.0.103.0, Culture=neutral, PublicKeyToken=null](arg:0)
 01:23:17   GameMenu Unregister Assembly: [package.facepunch.testbed.editor, Version=0.0.107.0, Culture=neutral, PublicKeyToken=null](arg:0)
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Cannot bind to the target method because its signature is not compatible with that of the delegate type.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a static method.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a static method.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Cannot bind to the target method because its signature is not compatible with that of the delegate type.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Cannot bind to the target method because its signature is not compatible with that of the delegate type.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Cannot bind to the target method because its signature is not compatible with that of the delegate type.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Cannot bind to the target method because its signature is not compatible with that of the delegate type.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Cannot bind to the target method because its signature is not compatible with that of the delegate type.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Cannot bind to the target method because its signature is not compatible with that of the delegate type.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Cannot bind to the target method because its signature is not compatible with that of the delegate type.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Cannot bind to the target method because its signature is not compatible with that of the delegate type.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Cannot bind to the target method because its signature is not compatible with that of the delegate type.
 01:23:17   hotload/GameMenu Unable to find matching substitution for a lambda method.
 01:23:17   hotload/GameMenu Cannot bind to the target method because its signature is not compatible with that of the delegate type.
 01:23:17   hotload/GameMenu Type handle 'GameObject' and method handle with declaring type 'GameObject' are incompatible. Get RuntimeMethodHandle and declaring RuntimeTypeHandle off the same MethodBase.
 01:23:17   hotload/GameMenu Type handle 'GameObject' and method handle with declaring type 'GameObject' are incompatible. Get RuntimeMethodHandle and declaring RuntimeTypeHandle off the same MethodBase.
 01:23:17   hotload/GameMenu  [17] Field '<GameObjects>k__BackingField' defined on type 'SceneFile' is not a field on the target object which is of type 'SceneFile'.
 01:23:17   hotload/GameMenu  [4] Field 'handleTexture' defined on type 'GameObject' is not a field on the target object which is of type 'PrefabScene'.
 01:23:17   hotload/GameMenu  [1] Field 'handleTexture' defined on type 'GameObject' is not a field on the target object which is of type 'Scene'.
 01:23:17   hotload/GameMenu Field 'handleTexture' defined on type 'GameObject' is not a field on the target object which is of type 'GameObject'.
 01:23:17   hotload/GameMenu The value "GameObject:Map" is not of type "GameObject" and cannot be used in this generic collection. (Parameter 'value')
 01:23:17   hotload/GameMenu Field 'handleTexture' defined on type 'GameObject' is not a field on the target object which is of type 'GameObject'.
 01:23:17   hotload/GameMenu The value "GameObject:Map" is not of type "GameObject" and cannot be used in this generic collection. (Parameter 'value')
 01:23:17   hotload/GameMenu Field 'handleTexture' defined on type 'GameObject' is not a field on the target object which is of type 'GameObject'.
 01:23:18   GameMenu Register Assembly: [package.facepunch.testbed, Version=0.0.108.0, Culture=neutral, PublicKeyToken=null](arg:0)
 01:23:18   GameMenu Register Assembly: [package.facepunch.testbed.editor, Version=0.0.109.0, Culture=neutral, PublicKeyToken=null](arg:0)
```

**Comment by LiminalCrab** [comment]
Disabling these settings in my Visual Studio appear to have resolved this problem for me. I will report back if it starts happening again.

![Screenshot 2023-11-08 135355](https://github.com/sboxgame/issues/assets/78995156/2b2099d8-21ff-4d47-ad10-af572997c35f)

**Comment by LiminalCrab** [comment]
Disregard my last comment, issue remains unresolved.
