### ISSUE TITLE
`sbox-server.exe`: Executing recently updated game on `asset.party` throw `Error loading package.base.dll`

### ISSUE THREAD

**Issue by PolSpock** [sboxgame/issues#4136]
### Describe the bug

Hi,

Since a recent update of s&box, if you try to start a server based on a recently updated game from `asset.party`, the `sbox-server.exe` console will throw these errors :
```
09:58:52 PackageL Whitelist Error: One or more errors occurred. (Object reference not set to an instance of an object.)
  at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)

  at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)

  --- End of stack trace from previous location ---

  at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)

  at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)

  at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)

  at Sandbox.AccessControl.TestType(TypeDefinition type)

  at Sandbox.AccessControl.TestTypeInThread(TypeDefinition type)
09:58:52 PackageL Whitelist Error: Sandbox.GradientFogEntity.UpdateFogState(..) - [None]        Missing method 'Void Color..ctor(Single ByRef, Single ByRef)'
09:58:52 PackageL Whitelist Error: Sandbox.GradientFogEntity.TickFrame(..) - [None]     Missing method 'Void Color..ctor(Single ByRef, Single ByRef)'
09:58:52 PackageL Couldn't load package.base - access control error
09:58:52 Interop  Error loading package.base.dll
```

It's problematic because we cannot debug a game with friends now (also mention for this issue https://github.com/sboxgame/issues/issues/4131)

### To Reproduce

1) Download https://github.com/Facepunch/sandbox
2) Edit his `.sbproj` with custom organization/ident in order to push it on `asset.party`
3) Push on `asset.party`
4) Try to launch a `sbox-server.exe` with this recently updated game on `asset.party`
(so something like this `.\sbox-server.exe +gamemode garrycity.sandboxservertest +map facepunch.flatgrass +maxplayers 64 +hostname Testo`)
5) The same stack of errors appears in your console

N.B.: if you run not recently updated game, you will not get the error (for example `facepunch.sandbox` or `facepunch.gunfight` at the time where i'm writing these lines)

### Expected behavior

Executing sbox-server must work

### Media/Files

![image](https://github.com/sboxgame/issues/assets/5229571/349f1598-475f-41ed-ad25-6eb33455c1d1)

### Additional context

I'm not running on `https://github.com/Facepunch/sbox-scenestaging/`

**Comment by garrynewman** [comment]
Sounds like the server might be out of date

**Comment by PolSpock** [comment]
Have you made any changes?

My last update of my `sbox-server.exe` was at 9:17 (UTC+1), i've just run again the update cmd (`.\steamcmd +force_install_dir c:\steamcmd\sboxserver +login anonymous +app_update 1892930 validate +quit`)
and now the error has gone
