### ISSUE TITLE
NRE When right clicking on a new scene.

### ISSUE THREAD

**Issue by yuberee** [sboxgame/issues#4152]
### Describe the bug

I created a new scene, but right clicking on the scene to add objects does nothing and prints the following error:
```Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at GameObjectNode.<>c.<CreateObjectMenu>b__20_3(PrefabFile x) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Scene\SceneTree\GameObjectNode.cs:line 363
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at GameObjectNode.CreateObjectMenu(Menu menu, Action`1 then) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Scene\SceneTree\GameObjectNode.cs:line 360
   at SceneNode.OnContextMenu() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Scene\SceneTree\SceneNode.cs:line 75
   at Editor.TreeView.OnItemContextMenu(VirtualWidget pressedItem, MouseEvent e) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Widgets\TreeView\TreeView.cs:line 338
   at Editor.BaseItemWidget.OnMousePress(MouseEvent e) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Widgets\BaseItemWidget.cs:line 365
   at Editor.Widget.InternalMousePressEvent(QMouseEvent e)
   at Managed.SourceTools.Exports.Editor_BaseScrollWidget_InternalMousePressEvent(UInt32 self, IntPtr e)
```

### To Reproduce

1. Create new scene
2. Right click on the scene inside of the Hierarchy to add a new object
3. Observe the console

### Expected behavior

For the dropdown list to pop up

### Media/Files

https://github.com/sboxgame/issues/assets/59583743/e10ef3b0-3498-430b-8670-2f92de5c0af4

### Additional context

I'm fixing and porting a very old game to the scene system but I'm not sure if it would have anything to do with this.

**Comment by yuberee** [comment]
This has suddenly stopped happening after a few restarts.
I'll keep the issue up in case I find a way to reproduce it.

**Comment by trundlr** [comment]
I'm getting this too on a brand new game.

**Comment by yuberee** [comment]
This has started happening again 😅

**Comment by trundlr** [comment]
It actually stopped for me 😹

**Comment by garrynewman** [comment]
This should be fixed in the next update
